
server:
  port: 8081

spring:
  application:
    name: kafka-producer
  kafka:
    bootstrap-servers: 192.168.0.6:9092
    producer:
#      bootstrap-servers: 192.168.0.6:9092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
