server:
  port: 9090
spring:
  application:
    name: quartz-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.gochanghai.com:3306/quartz_center?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: false
        login-username: admin
        login-password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mail:
#  fromMail:
#    addr: gochanghai@aliyun.com

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: com.gochanghai.springboot.entity
#  type-enums-package: com.gochanghai.springboot.enums
#  global-config:
#    db-config:
#      id-type: auto
#      field-strategy: 2
#      capital-mode: true
#      column-underline: true
#      logic-delete-value: 1
#      logic-not-delete-value: 0

quartz:
  scheduler:
    instance-name: MyselfScheduler
    instance-id: NON_CLUSTERED # 使用集群：AUTO 不使用集群：NON_CLUSTERED
    skip-update-check: true
    job-factory:
      class: org.quartz.simpl.SimpleJobFactory
  job-store:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    datasource: quartzDataSource
    table-prefix: QRTZ_
    is-clustered: true
  thread-pool:
    class: org.quartz.simpl.SimpleThreadPool
    thread-count: 5
  datasource:
    quartzDataSource:
      driver: ${spring.datasource.druid.driver-class-name}
      url: ${spring.datasource.druid.url}
      user: ${spring.datasource.druid.username}
      password: ${spring.datasource.druid.password}
      maxConnections: 5
      validationQuery: select 0
      connection-provider:
        class: com.lingdu.welend.config.quartz.DruidConnectionProvider