############################# 访问路径、端口tomcat start #############################
server:
  port: 8001
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
############################# 访问路径、端口tomcat end ###############################

################################ spring config start ###############################
spring:
  application:
    name: ccims-com.lch.ccims.redismq.commons
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ################################ redismq begin ##################################
  redis:
    database: 1
    host: 192.168.0.103
    port: 6379
    password: zwjk#Dev
    timeout: 10s
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
      shutdown-timeout: 3s
  ################################ redismq stop ##################################
################################ spring config end #################################