server:
  port: 9090

spring:
  application:
   name: dubbo-provider

#\u6307\u5B9A\u5F53\u524D\u670D\u52A1/\u5E94\u7528\u7684\u540D\u5B57\uFF08\u540C\u6837\u7684\u670D\u52A1\u540D\u5B57\u76F8\u540C\uFF0C\u4E0D\u8981\u548C\u522B\u7684\u670D\u52A1\u540C\u540D\uFF09
dubbo:
  application:
   name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://www.gochanghai.com:2181
  provider:
    timeout: 1000

demo:
  service:
   version: 1.0.0