server:
  port: 9091
spring:
  application:
    name: cloud-web
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.6:8848
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"