################################ spring config start ###############################
spring:
  application:
    name: demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ################################ redismq begin ##################################
  redis:
    database: 1
    host: 192.168.0.6
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8
      shutdown-timeout: 3s
  ################################ redismq stop ##################################
################################ spring config end #################################